### ISSUE TITLE
create issues based on lab in-person meeting

### ISSUE THREAD

**Issue by v5y8** [UBC-MDS/DSCI_522_Group_302#1]
Please make issues based on the meeting on Thursday, January 16, 2020

**Comment by carlinakim** [comment]
Tasks for Milestone 1
- Teamwork Contract (Derek)
-  Code of Conduct (James)
-  Project proposal
    - describe data set (Rob)
    - research question (Rob)
    - plan of data analysis (Rob)
    - EDA discussion (Derek & Carlina)
    - suggest report format (James)
-  Contribution file (James)
- Data downloading Script (James)
- EDA report Jupyternotebook (Derek & Carlina)
- Update Readme.md in group repo (James) 
    ~- (include instructions for kaggle)~
- Set up repo structure (Carlina)

**Comment by v5y8** [comment]
the whiteboard notes from the meeting:
![Session 2020-01-16 3_00 p m  (1)](https://user-images.githubusercontent.com/11624344/72667042-85da2880-39cc-11ea-97f7-e5816f68e26a.jpg)
![Session 2020-01-16 3_00 p m](https://user-images.githubusercontent.com/11624344/72667043-8672bf00-39cc-11ea-9635-1009d2c954c0.jpg)

**Comment by RobBlumberg** [comment]
Closing as we have made issues for all tasks
