### ISSUE TITLE
Set up repo structure

### ISSUE THREAD

**Issue by carlinakim** [UBC-MDS/DSCI_522_Group_302#2]
add folders into the repo in the following structure
-docs
-imgs
-src
*update* I cannot add empty folders into git so we will have to create these folders as we create the files that belong in the respective folders!

**Comment by carlinakim** [comment]
Hey guys, I cannot add empty folders into git so we will have to create these folders as we create the files that belong in the respective folders!

**Comment by v5y8** [comment]
maybe you could leave an empty place holder file? like src/place_holder.py and such?

**Comment by RobBlumberg** [comment]
Closing this as we are creating directories adhoc
