### ISSUE TITLE
Data pulling script

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_522_Group_302#3]
Creating this issue for things related to data script

**Comment by RobBlumberg** [comment]
A point came up that I think we should consider. So normally you don't want to do EDA using any test data, because it could lead to making assumptions on the test data and then producing a model that is biased. 

So I guess we should create a test data set that is separate from the rest of the training data, and then only look at the test data set at the end to evaluate the final model we produce.  

In the data pulling script, we could divide the entire dataset into training and test and then EDA would be done only on the training set?

**Comment by v5y8** [comment]
specifications:

invocation: `python pull_data.py <URL> <filepath>`

input: 
- `URL`: the URL where the data file is hosted at.
- `filepath`: the location on the local machine where the user would like the file to be downloaded to.

returns:
- two files, named `<file_name>_train` and `<file_name>_test`, downloaded to the specified filepath during the invocation of the script.
