### ISSUE TITLE
Milestone 3 prospective changes

### ISSUE THREAD

**Issue by RobBlumberg** [UBC-MDS/DSCI_522_Group_302#38]
Creating this issue for things that came up during milestone 2 that we plan to change / improve for milestone 3.

- Get R^2 on test set to go directly in report
- Center kable in final report

Please add anything else you think of that I didn't list

**Comment by dkruszew** [comment]
EDA.py script doesn't work without chrome installed. Altair plots use chrome driver. See below for details:
https://altair-viz.github.io/user_guide/saving_charts.html
