### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group_302#67]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] It would really have helped if you had a caption and a figure/table number for each plot. That way you can easily reference it in your text, and it's easier for readers to find
- - [x] Figure 1:
	- - [x] Nice! This is a very powerful visualization that shows the reader exactly what you want to show
	- - [x] You should round all values to 2 sig figs? will probably make it less messy and easier to read
	- - [x] Consider setting diagonal values on your correlation map to be 0 or nan; those will really stand out otherwise.
	- - [x] Ideally, you only want to show half the correlation map as the other half is redundant (see example [here](http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-correlation-matrix-heatmap-add-correlation-coefficients-1.png)) - let me know if you figure out how to do this in Altair
- - [x] Figure 2:
	- - [x] Definitely switch x and y so categorical axes are on the y-axis and it's easier to read
	- - [x] You should rotate all x-axis labels so they're oriented correctly: `alt.X('Var:N', axis=alt.Axis(labelAngle=0))`
	- - [x] Consider sorting the countries by your metric like [here](https://github.com/altair-viz/altair/issues/1137#issuecomment-458236850) 
- - [x] Figure 3:
	- - [x] Looks great! nice work
- - [x] Figure 4:
	- - [x] Defend the choice (not in your report, I mean in this issue) to connect the lines together; is this correct for your context?
	- - [x] Consider removing the gray background with theme_bw()!
- - [x] Tables
	-  - [x] Too many sig figs, there's no need to show that many, it hurts readability and interpretability
- - [x] remove the top and right axes in your matplotlib (I think) plot. See [here](https://matplotlib.org/examples/ticks_and_spines/spines_demo.html) how to do it
- - [x] This is not something standard, but I personally would have created a dictionary with the column names as keys and a more human readable name as a value, then when plotting use the human readable names. This is probably too much work to do at this point, just something to keep in mind in the future. The feature names aren't super intuitive so you have to hunt around in the text for their interpretation. Another way is to add a table in the appendix with the column name and its corresponding human readable interpretation
- - [x] Overall the report looks very polished and clean! Great work! Excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by RobBlumberg** [comment]
We have made most of the changes suggested here. 

First we added figure captions to all plots and tables.

For fig1, we now keep only 1 sig fig, and set diagonal values to 0. Unfortunately, the redundant repeated correlation scores was not addressed due to time constraints.

For fig2, we put the categorical feature on the y-axis. We did not get to sorting the values by a specific metric. 

For fig4, we changed to a scatter plot so that we don't have meaningless connected lines.

For the table, we reduced the number of decimals to 3.

For fig 5, we removed the top and right axes.

We also added a reference table in the appendix explaining each feature.

Thanks for the feedback! It has definitely helped improve the quality of our report.

**Comment by firasm** [comment]
Good work ! Nice work prioritizing the important ones over the extra "nice-to-haves"

**Comment by firasm** [comment]
FYI for **future** reference, here's a full code chunk to get rid of the redundant correlations (note also the `.round(2)` function that rounds values to 2 digits

```
## Section 2: Lower triangle of correlation plot with no diagonals

# This bit of wrangling creates a new dataframe with only half the elements
l1 = sorted(df_iris.corr().columns.to_list()) # sorting is needed to make sure the final correlation maps looks like an upper or lower triangle
l2 = l1.copy()
rows = []

for e1 in l1:
    for e2 in l2:
        rows.append([e1,e2, df_iris.corr().loc[e1,e2]])
    l2.remove(e1)
    
# Create dataframe from list of rows
newdf = pd.DataFrame(rows,columns=['Var1','Var2','Corr'])

# If you want to remove the diagonals
newdf = newdf[newdf['Var1']!=newdf['Var2']]

# Create the heatmap first
heatmap = alt.Chart(newdf).mark_rect(
).encode(
    alt.X('Var1:O', title = ''),
    alt.Y('Var2:O', title = '', axis=alt.Axis(labelAngle=0)),
     alt.Color('Corr:Q',
                scale=alt.Scale(scheme='viridis'))
)

# Add the correlation values as a text mark
text = heatmap.mark_text(baseline='middle', fontSize=20).encode(
    text=alt.Text('Corr:Q', format='.2'),
    color=alt.condition(
        alt.datum['Corr'] >= 0.95,
        alt.value('black'),
        alt.value('white')
    )
)

# Set the height, width, title and other properties
corrMatrix_chart = (heatmap + text).properties(
    width = 400,
    height = 400,
    title = "Iris variables correlation matrix",
)
corrMatrix_chart.configure_axis(
    labelFontSize=18,
    titleFontSize=24,
).configure_title(
    fontSize=24,
    anchor='start',
).configure_legend(
    labelFontSize=20,
    titleFontSize=20)
```

![visualization-18](https://user-images.githubusercontent.com/2507459/74092067-2ecbee80-4a74-11ea-9df7-4db5d839ee93.png)
