### ISSUE TITLE
EDA report Jupyternotebook 

### ISSUE THREAD

**Issue by carlinakim** [UBC-MDS/DSCI_522_Group_302#7]
This issue is for all EDA related content. Couple things needed to be done (add more as needed):
-Cleaning & Wrangling  Datas files
-Merging 4 files with necessary content into one mega-dataset
-Making plots/figures

**Comment by RobBlumberg** [comment]
Ultimately we should have a script that automates the merging / cleaning and outputs the combined dataset, but for the purposes of milestone1, we could just do it in the EDA notebooks?

**Comment by v5y8** [comment]
I agree. there's always time to refactor code from a notebook into a script in other sprints.
I've also made some rudimentary attempts at merging the dataframes in my attempt on #3 , you can check to see if I need to fix anything.

**Comment by RobBlumberg** [comment]
My only feedback on the initial EDA drafts would be that I think maybe a few of the plots should be touched up to adhere to principles of effective plotting (like descriptive axis labels, and having titles for all plots). I know these aren't final plots but I think it's still worth doing. Other than that, we just need to summarize the EDA findings in the proposal.

One other thing is that the plot showing plc vs winodds is pretty overcrowded. I think a simple line chart showing average finish vs winodds would be more clear. 

What do you think? Also, I don't have much work so I could take on these tasks.

**Comment by dkruszew** [comment]
I agree Rob, you can do this work.
