### ISSUE TITLE
Milestone 4 To Dos

### ISSUE THREAD

**Issue by dkruszew** [UBC-MDS/DSCI_522_Group_302#72]
**High Priority**
- 4 Docker Files (Pooled into One)
- Docker Hub Repository
- Update README.md:
    a) Add Makefile dependency diagram  
    b) Docker instructions

**Low Priority**
- Captions in Final Report
- Round tables to 2 sig figs
- Set diagonal values on correlation map to 0 or nan
- Other figure tweaks from feedback
- Download script tests/asserts

**Comment by RobBlumberg** [comment]
Most feedback changes have been made. All that is left is to add figure captions, which I'll address now

**Comment by RobBlumberg** [comment]
Feedback has now all been addressed.
